settings:
  title: 'Status Page'
  url: 'https://status.fandi.us.kg' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cdn
    name: CDN
    url: 'https://cdn.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: anime-api
    name: Anime API
    url: 'https://anime.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: komik-api
    name: Komik API
    url: 'https://komik.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: swagger-api
    name: API
    url: 'https://api.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: kana-whatsapp-bot
    name: Kana (Whatsapp Bot)
    url: 'https://kana.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: dinime-whatsapp-bot
    name: Dinime (Whatsapp Bot)
    url: 'https://ruka.fandi.my.id/'
    method: GET
    expectStatus: 200

  - id: dinime-telegram-bot
    name: Dinime (Telegram Bot)
    url: 'https://telebot.fandi.my.id/'
    method: GET
    expectStatus: 200
